virtualStoreType: global

minimumReleaseAgeExclude:
  - "@mr-hope/*"
  - "@oxfmt/*"
  - "@oxlint/*"
  - "@oxlint-tsgolint/*"
  - "oxc-config-hope"
  - "oxfmt"
  - "oxlint"
  - "oxlint-tsgolint"
  - "tsdown"

trustPolicy: no-downgrade
minimumReleaseAgeExcludePrune: true
trustPolicyExcludePrune: true
trustPolicyIgnoreAfter: 720
